apiVersion: v1
kind: Service
metadata:
  name: lead-gen-tool
  labels:
    app: lead-gen-tool
spec:
  type: LoadBalancer
  selector:
    app: lead-gen-tool
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
